/* 
This project showcases a series of SQL queries built on a fictional SaaS database  
containing four core tables: users, events, payments, and marketing_spend.

The aim of this project is to demonstrate my ability to write clean, analytical SQL  
and to apply it toward calculating key SaaS performance metrics, including:

- Daily Active Users (DAU)
- Monthly Active Users (MAU)
- Churn rate
- Customer Acquisition Cost (CAC)
- Lifetime Value (LTV)
- Annual Recurring Revenue (ARR)

By constructing and querying this dataset, I aim to illustrate my understanding of 
how SaaS metrics are derived from real-world product, billing, and marketing data.
*/


/* DAU - Daily Active Users*/
/* A count of unique users per day(date_active) */ 
SELECT event_date, COUNT(DISTINCT user_id) AS DAU
FROM events
GROUP BY event_date
ORDER BY event_date;

/* MAU - Monthly Active Users */ 
/* A count of unique users per month(start of month to end of month) */ 
SELECT event_date, COUNT(DISTINCT user_id) AS MAU
SELECT 
    DATE_TRUNC('month', event_date) AS activity_month,
    COUNT(DISTINCT user_id) AS monthly_unique_users
FROM 
    events
WHERE 
    event_date >= '2025-01-01' 
    AND event_date < '2025-02-01'
GROUP BY 
    activity_month;

/* Churn - Churn is the percentage of users lost. Those users who cancelled their subscriptions */
/* Churn = Number of customers lost during a period / Total customers at the start of the period */
SELECT
    CAST(SUM(CASE WHEN subscription_status = 'cancelled' THEN 1 ELSE 0 END) AS NUMERIC) / 
    COUNT(*) AS cancellation_rate
FROM
    users;
	-- Churn comes out to be 0.25 or 25% 

/*CAC - Customer Acquistion Cost */
/* CAC = New Users Acquired/Marketing Spend */
WITH new_users AS (
    SELECT 
        DATE_TRUNC('month', signup_date) AS signup_month,
        acquisition_channel,
        COUNT(*) AS new_customers
    FROM users
    GROUP BY 1,2
),

spend AS (
    SELECT 
        spend_month,
        acquisition_channel,
        amount AS marketing_spend
    FROM marketing_spend
)

SELECT
    n.signup_month,
    n.acquisition_channel,
    marketing_spend,
    new_customers,
    marketing_spend * 1.0 / NULLIF(new_customers, 0) AS cac
FROM new_users n
LEFT JOIN spend s
    ON n.signup_month = s.spend_month
    AND n.acquisition_channel = s.acquisition_channel
ORDER BY signup_month, acquisition_channel;

/* LTV - Life Time Value */
/* LTV = Total revenue generated by a user */
SELECT
    user_id,
    SUM(amount) AS ltv
FROM payments
GROUP BY user_id
ORDER BY user_id;

/* ARR - Annual Recurring Revenvue */
/* ARR = SUM(monthly_price * 12) for all ACTIVE subscriptions */

SELECT SUM(amount * 12) AS ARR
FROM 
(SELECT *
FROM payments
JOIN users
ON payments.user_id = users.user_id)
WHERE subscription_status = 'active';